/**
 * @fileoverview Core Integrity & Hash Chaining Module for Git History LLM.
 * @module core/integrity
 * 
 * @description
 * This module provides end-to-end cryptographic integrity verification for commit summaries,
 * metadata, and structural insights generated by the Git History LLM pipeline.
 * It utilizes SHA-256 hash chaining (similar to a blockchain ledger) to ensure that
 * all processed outputs are verifiable, tamper-resistant, and protected against 
 * silent corruption during transit or storage in downstream Zayvora pipelines.
 * 
 * Features:
 * - Deterministic JSON stringification for consistent hashing of JS objects.
 * - Cryptographic hash generation (SHA-256/SHA-512).
 * - Linked hash chaining (each output node references the previous node's hash).
 * - Merkle Root generation for batch verification.
 * - Strict validation and tamper detection.
 */

const crypto = require('crypto');

/**
 * Custom error class for integrity validation failures.
 * Thrown when a hash mismatch, chain breakage, or data corruption is detected.
 */
class IntegrityVerificationError extends Error {
    /**
     * @param {string} message - Description of the validation failure.
     * @param {Object} [details={}] - Additional context regarding the failure.
     */
    constructor(message, details = {}) {
        super(message);
        this.name = 'IntegrityVerificationError';
        this.details = details;
        Error.captureStackTrace(this, this.constructor);
    }
}

/**
 * Custom error class for schema or input validation failures.
 */
class IntegrityInputError extends Error {
    constructor(message) {
        super(message);
        this.name = 'IntegrityInputError';
        Error.captureStackTrace(this, this.constructor);
    }
}

/**
 * Deterministically stringifies a JavaScript object by sorting its keys recursively.
 * This ensures that objects with the same data but different key insertion orders
 * will produce the exact same cryptographic hash.
 * 
 * @param {any} obj - The data to stringify.
 * @returns {string} The deterministically stringified JSON.
 */
function deterministicStringify(obj) {
    if (obj === null || typeof obj !== 'object') {
        return JSON.stringify(obj);
    }

    if (Array.isArray(obj)) {
        const arrStr = obj.map(item => deterministicStringify(item)).join(',');
        return `[${arrStr}]`;
    }

    const sortedKeys = Object.keys(obj).sort();
    const keyValPairs = sortedKeys.map(key => {
        const val = deterministicStringify(obj[key]);
        return `"${key}":${val}`;
    });

    return `{${keyValPairs.join(',')}}`;
}

/**
 * Represents a single verifiable node (block) in the integrity chain.
 * Wraps the raw commit data/summary with cryptographic metadata.
 */
class IntegrityNode {
    /**
     * @param {Object} data - The raw payload (e.g., commit summary, metadata).
     * @param {string} previousHash - The SHA-256 hash of the preceding node in the chain.
     * @param {string} [algorithm='sha256'] - The hashing algorithm used.
     */
    constructor(data, previousHash, algorithm = 'sha256') {
        if (data === undefined) {
            throw new IntegrityInputError('Data payload cannot be undefined.');
        }
        if (typeof previousHash !== 'string') {
            throw new IntegrityInputError('Previous hash must be a string.');
        }

        this.timestamp = new Date().toISOString();
        this.algorithm = algorithm;
        this.previousHash = previousHash;
        this.data = data;
        this.hash = this.calculateHash();
    }

    /**
     * Calculates the cryptographic hash of the node's current state.
     * Includes the timestamp, previous hash, and the deterministically stringified data.
     * 
     * @returns {string} The hexadecimal hash string.
     */
    calculateHash() {
        const payload = deterministicStringify({
            timestamp: this.timestamp,
            previousHash: this.previousHash,
            data: this.data
        });

        return crypto
            .createHash(this.algorithm)
            .update(payload, 'utf8')
            .digest('hex');
    }

    /**
     * Verifies the integrity of this specific node.
     * Recalculates the hash and compares it against the stored hash.
     * 
     * @returns {boolean} True if the node is valid and untampered.
     * @throws {IntegrityVerificationError} If the hash does not match the payload.
     */
    verify() {
        const recalculated = this.calculateHash();
        if (recalculated !== this.hash) {
            throw new IntegrityVerificationError(
                'Node integrity verification failed. Data corruption detected.',
                {
                    expectedHash: this.hash,
                    actualHash: recalculated,
                    timestamp: this.timestamp
                }
            );
        }
        return true;
    }

    /**
     * Serializes the node to a plain JavaScript object for storage/transmission.
     * 
     * @returns {Object}
     */
    toJSON() {
        return {
            timestamp: this.timestamp,
            algorithm: this.algorithm,
            previousHash: this.previousHash,
            hash: this.hash,
            data: this.data
        };
    }

    /**
     * Reconstructs an IntegrityNode from a parsed JSON object.
     * 
     * @param {Object} parsedObject - The parsed JSON representation of a node.
     * @returns {IntegrityNode} The reconstructed node.
     */
    static fromJSON(parsedObject) {
        const node = new IntegrityNode(parsedObject.data, parsedObject.previousHash, parsedObject.algorithm);
        // Override generated properties with the stored ones to allow verification
        node.timestamp = parsedObject.timestamp;
        node.hash = parsedObject.hash;
        return node;
    }
}

/**
 * Orchestrates the end-to-end integrity chain for a sequence of commit summaries.
 * Acts as an immutable ledger ensuring that no historical commit analysis can be
 * altered without invalidating the entire subsequent chain.
 */
class IntegrityChain {
    /**
     * Initializes a new IntegrityChain.
     * 
     * @param {string} [genesisData='GIT_HISTORY_LLM_GENESIS'] - Seed data for the genesis block.
     * @param {string} [algorithm='sha256'] - The hashing algorithm to use for the chain.
     */
    constructor(genesisData = 'GIT_HISTORY_LLM_GENESIS', algorithm = 'sha256') {
        this.algorithm = algorithm;
        this.chain = [];
        
        // Create the genesis block (the foundation of the chain)
        // Genesis block has a hardcoded previousHash of exactly 64 zeros (for SHA-256)
        const genesisPreviousHash = '0'.repeat(64);
        const genesisNode = new IntegrityNode({ genesis: genesisData }, genesisPreviousHash, this.algorithm);
        this.chain.push(genesisNode);
    }

    /**
     * Retrieves the latest node added to the chain.
     * 
     * @returns {IntegrityNode} The most recent node.
     */
    getLatestNode() {
        return this.chain[this.chain.length - 1];
    }

    /**
     * Seals a new piece of data (e.g., a processed commit summary) into the chain.
     * 
     * @param {Object} commitSummary - The processed insight/metadata to secure.
     * @returns {IntegrityNode} The newly created and sealed node.
     */
    seal(commitSummary) {
        const previousNode = this.getLatestNode();
        const newNode = new IntegrityNode(commitSummary, previousNode.hash, this.algorithm);
        this.chain.push(newNode);
        return newNode;
    }

    /**
     * Validates the entire chain from genesis to the latest node.
     * Checks both individual node integrity and the linking between nodes.
     * 
     * @returns {boolean} True if the entire chain is valid.
     * @throws {IntegrityVerificationError} If any node is tampered with or links are broken.
     */
    verifyEntireChain() {
        for (let i = 0; i < this.chain.length; i++) {
            const currentNode = this.chain[i];
            
            // 1. Verify the internal consistency of the node itself
            currentNode.verify();

            // 2. Verify the chain link (skip for genesis block)
            if (i > 0) {
                const previousNode = this.chain[i - 1];
                if (currentNode.previousHash !== previousNode.hash) {
                    throw new IntegrityVerificationError(
                        `Chain link broken at index ${i}.`,
                        {
                            nodeIndex: i,
                            expectedPreviousHash: previousNode.hash,
                            actualPreviousHash: currentNode.previousHash
                        }
                    );
                }
            }
        }
        return true;
    }

    /**
     * Generates a Merkle Root hash for the current state of the chain.
     * Useful for O(1) verification of the entire dataset's state in downstream Zayvora pipelines.
     * 
     * @returns {string} The Merkle Root hash.
     */
    generateMerkleRoot() {
        if (this.chain.length === 0) return null;

        let hashes = this.chain.map(node => node.hash);

        while (hashes.length > 1) {
            // If the number of hashes is odd, duplicate the last one to make it even
            if (hashes.length % 2 !== 0) {
                hashes.push(hashes[hashes.length - 1]);
            }

            const nextLevel = [];
            for (let i = 0; i < hashes.length; i += 2) {
                const combined = hashes[i] + hashes[i + 1];
                const newHash = crypto
                    .createHash(this.algorithm)
                    .update(combined, 'utf8')
                    .digest('hex');
                nextLevel.push(newHash);
            }
            hashes = nextLevel;
        }

        return hashes[0];
    }

    /**
     * Exports the entire chain to a JSON-serializable array.
     * 
     * @returns {Object[]} Array of serialized nodes.
     */
    export() {
        return this.chain.map(node => node.toJSON());
    }

    /**
     * Imports an existing chain from a JSON array, verifying it during the process.
     * 
     * @param {Object[]} serializedChain - The exported chain array.
     * @param {string} [algorithm='sha256'] - The hashing algorithm expected.
     * @returns {IntegrityChain} The reconstructed and verified chain instance.
     * @throws {IntegrityVerificationError} If the imported chain is invalid.
     */
    static import(serializedChain, algorithm = 'sha256') {
        if (!Array.isArray(serializedChain) || serializedChain.length === 0) {
            throw new IntegrityInputError('Invalid serialized chain provided for import.');
        }

        const instance = new IntegrityChain('TEMP', algorithm);
        // Clear the default genesis block created by the constructor
        instance.chain = [];

        for (const item of serializedChain) {
            const node = IntegrityNode.fromJSON(item);
            instance.chain.push(node);
        }

        // Immediately verify the imported chain to guarantee trust
        instance.verifyEntireChain();

        return instance;
    }
}

/**
 * Utility function to quickly generate a standalone hash for arbitrary data
 * without creating a full chain. Useful for quick integrity checks of single files.
 * 
 * @param {any} data - The data to hash.
 * @param {string} [algorithm='sha256'] - The hashing algorithm.
 * @returns {string} The hexadecimal hash.
 */
function generateStandaloneHash(data, algorithm = 'sha256') {
    const payload = deterministicStringify(data);
    return crypto
        .createHash(algorithm)
        .update(payload, 'utf8')
        .digest('hex');
}

module.exports = {
    IntegrityVerificationError,
    IntegrityInputError,
    deterministicStringify,
    IntegrityNode,
    IntegrityChain,
    generateStandaloneHash
};